<?php

declare(strict_types=1);

namespace vardumper\IbexaThemeTranslationsBundle\Cache;

/**
 * Writes per-language JSON and TypeScript files into the public/bundles directory
 * so headless front-ends can import them as static assets.
 *
 * The files are regenerated every time the translation cache is warmed up and
 * can be served directly by the web server without any PHP involvement.
 *
 * Output (example, language "ger-DE"):
 *   public/bundles/theme-translations/ger_DE.json
 *   public/bundles/theme-translations/ger_DE.ts
 */
final class PublicTranslationsCache implements TranslationCacheInterface
{
    public function __construct(
        private readonly string $outputDir,
    ) {
    }

    /**
     * Not used for runtime lookups — this cache tier is write-only.
     * Actual reading is done by the headless front-end consuming the static files.
     */
    public function get(string $languageCode, string $transKey): ?string
    {
        return null;
    }

    public function warmLanguage(string $languageCode, array $translations): void
    {
        if (!is_dir($this->outputDir)) {
            mkdir($this->outputDir, 0775, true);
        }

        $safe = $this->safeName($languageCode);
        $this->writeJson($safe, $translations);
        $this->writeTypeScript($safe, $languageCode, $translations);
    }

    public function invalidateLanguage(string $languageCode): void
    {
        $safe = $this->safeName($languageCode);

        foreach (['.json', '.ts'] as $ext) {
            $file = $this->outputDir . '/' . $safe . $ext;
            if (is_file($file)) {
                @unlink($file);
            }
        }
    }

    public function invalidateAll(): void
    {
        if (!is_dir($this->outputDir)) {
            return;
        }

        foreach ([...glob($this->outputDir . '/*.json'), ...glob($this->outputDir . '/*.ts')] as $file) {
            @unlink($file);
        }
    }

    private function writeJson(string $safeName, array $translations): void
    {
        $content = json_encode($translations, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) . "\n";
        $this->writeAtomic($this->outputDir . '/' . $safeName . '.json', $content);
    }

    private function writeTypeScript(string $safeName, string $languageCode, array $translations): void
    {
        $lines = [
            '// Auto-generated by theme-translations:cache:warmup',
            '// Language: ' . $languageCode,
            '// Do not edit manually.',
            '',
            'const translations: Record<string, string> = {',
        ];

        foreach ($translations as $key => $value) {
            $lines[] = '  ' . json_encode((string)$key) . ': ' . json_encode((string)$value) . ',';
        }

        $lines[] = '};';
        $lines[] = '';
        $lines[] = 'export default translations;';
        $lines[] = '';

        $this->writeAtomic($this->outputDir . '/' . $safeName . '.ts', implode("\n", $lines));
    }

    private function writeAtomic(string $file, string $content): void
    {
        $tmp = $file . '.' . uniqid('', true) . '.tmp';
        file_put_contents($tmp, $content);
        rename($tmp, $file);
    }

    private function safeName(string $languageCode): string
    {
        return preg_replace('/[^a-zA-Z0-9_-]/', '_', $languageCode);
    }
}
